# Generated by Django 5.0.6 on 2025-02-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255, unique=True)),
                ('schedule', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('current_school', models.CharField(max_length=255)),
                ('parent_info', models.TextField()),
                ('student_code', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('birth_date', models.DateField()),
                ('current_school', models.CharField(max_length=255)),
                ('teacher_code', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('transferred', 'Chuyển lớp'), ('dropout', 'Nghỉ hẳn')], default='active', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('class_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='authentication.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('transferred', 'Chuyển lớp'), ('dropout', 'Nghỉ hẳn')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('previous_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='authentication.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assigned', to='authentication.teacher'),
        ),
    ]
