# Generated by Django 5.0.6 on 2025-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Tên đầy đủ'),
        ),
    ]
