# Generated by Django 5.0.6 on 2025-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_student_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên lớp học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.TextField(verbose_name='Lịch học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_school',
            field=models.CharField(max_length=255, verbose_name='Trường đang theo học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_info',
            field=models.TextField(verbose_name='Thông tin phụ huynh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='current_school',
            field=models.CharField(max_length=255, verbose_name='Trường đang dạy'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Tên đầy đủ'),
        ),
    ]
