# Generated by Django 5.0.6 on 2025-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_class_class_name_alter_class_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Mã học viên'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Mã giảng viên'),
        ),
    ]
