# Generated by Django 5.0.6 on 2025-02-21 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_alter_class_teacher_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tên đầy đủ')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('birth_date', models.DateField(verbose_name='Ngày sinh')),
                ('current_school', models.CharField(max_length=255, verbose_name='Trường đang theo học')),
                ('parent_info', models.TextField(verbose_name='Thông tin phụ huynh')),
                ('student_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Mã học viên')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Tên đầy đủ')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('birth_date', models.DateField(verbose_name='Ngày sinh')),
                ('current_school', models.CharField(max_length=255, verbose_name='Trường đang dạy')),
                ('teacher_code', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Mã giảng viên')),
            ],
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='authentication.student'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='authentication.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_assigned', to='authentication.teacher'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
