# Generated by Django 5.0.6 on 2025-02-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_student_teacher_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthistory',
            name='previous_class',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_date',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='classes', to='authentication.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên lớp'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='authentication.teacher'),
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu học')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc học')),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('transferred', 'Chuyển lớp'), ('dropped', 'Nghỉ hẳn'), ('suspended', 'Bảo lưu')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('class_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_histories', to='authentication.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_histories', to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Thứ Hai'), ('Tuesday', 'Thứ Ba'), ('Wednesday', 'Thứ Tư'), ('Thursday', 'Thứ Năm'), ('Friday', 'Thứ Sáu'), ('Saturday', 'Thứ Bảy'), ('Sunday', 'Chủ Nhật')], max_length=10)),
                ('session', models.CharField(choices=[('Morning', 'Sáng'), ('Afternoon', 'Chiều')], max_length=10)),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phòng học')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='authentication.class')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='authentication.teacher')),
            ],
            options={
                'unique_together': {('class_assigned', 'day_of_week', 'session')},
            },
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='StudentHistory',
        ),
    ]
