# Generated by Django 5.0.6 on 2025-02-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
